image: java:8

pipelines:
  default:
    - step:
        caches:
          - gradle
        script: # Modify the commands below to build your repository.
          - cd PowerUProbot2018
          - bash ./gradlew build jacocoTestReport
