language: java
install: true
cache:
  directories:
  - /home/travis/.gradle
  - ~/Yertle2018/.gradle
  - ~/Template2018/.gradle
  - ~/PowerUProbot2018/.gradle

script: # Modify the commands below to build your repository.
  - cd Yertle2018
  - ./gradlew build jacocoTestReport
  - cd ../PowerUProbot2018
  - ./gradlew build jacocoTestReport
  - cd ../Template2018
  - ./gradlew clean build jacocoTestReport

notifications:
  slack: team281programming:mpBJ2mwOFaAywAQDGPA2GV8d
