image: java:8

pipelines:
  default:
    - step:
        caches:
          - gradle
        script: # Modify the commands below to build your repository.
          - cd Yertle2018
          - bash ./gradlew build jacocoTestReport
          - cd ..
          - cd PowerUProbot2018
          - bash ./gradlew build jacocoTestReport
          - cd ..
          - cd Template2018
          - bash ./gradlew clean build jacocoTestReport
